platform :ios, "8.0"
target 'JawboneUP' do
  
use_frameworks!
pod 'iOSDFULibrary'
pod 'AFNetworking'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod "SVProgressHUD-0.8.1"
pod 'PGDatePicker', '>= 1.4.0'
pod 'Masonry'
end


